apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-csi
provisioner: disk.csi.azure.com   # Azure Managed Disk CSI driver
reclaimPolicy: Retain            # Keep PV even if PVC is deleted
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  skuname: Premium_LRS            # Can also use Standard_LRS or Premium_ZRS

