apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fitness-tracker-pvc
  namespace: fitness-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 10Gi
